export const ADD_PRODUCT_REQUESTING = "ADD_PRODUCT_REQUESTING";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTING = "DELETE_PRODUCT_REQUESTING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";
